# Generated by Django 5.0.7 on 2024-07-19 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coupons", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coupon",
            options={"verbose_name": "Купон", "verbose_name_plural": "Купоны"},
        ),
        migrations.AlterField(
            model_name="coupon",
            name="active",
            field=models.BooleanField(verbose_name="Активен"),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="code",
            field=models.CharField(max_length=50, unique=True, verbose_name="Код"),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="discount",
            field=models.IntegerField(
                help_text="Процентное значение (от 0 до 100)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Скидка",
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="valid_from",
            field=models.DateTimeField(verbose_name="Срок начала действия"),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="valid_to",
            field=models.DateTimeField(verbose_name="Срок окончания действия"),
        ),
    ]
